spring.application.name=Incidencias
server.port=8082
spring.mvc.format.date-time=iso

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/db_incidencias?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

uri.url=${URI_URL:https://securityauth-production.up.railway.app}
migue.url=${MIGUE_URL:http://192.9.245.X:8083}
migue2.url=${MIGUE2_URL:http://Evidencias-env.eba-ayhhwii6.us-east-1.elasticbeanstalk.com}
liz.url=${LIZ_URL:http://165.1.74.X:8085}
liz2.url=${LIZ2_URL:http://Notificaciones-env.eba-jm4kv3hv.us-east-1.elasticbeanstalk.com}

eureka.client.serviceUrl.defaultZone=${EUREKA_URL:https://eurekaskybridge-production.up.railway.app/eureka/}
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=${PUBLIC_IP:127.0.0.1}

weather.api.key=X

mapstruct.defaultComponentModel=spring
springdoc.packagesToScan=edu.tecnm.controller
spring.cloud.openfeign.circuitbreaker.enabled=true
